/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Flow.info;
import java.awt.*;
import java.io.File;
import java.util.regex.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author ram.a
 */
public class InputPanel extends javax.swing.JPanel {

    /**
     * Creates new form InputPanel
     */
    info Info;
    public InputPanel(info Info) {
        initComponents();
        this.Info= Info;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblTelephone = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        lblLicense = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblHealth = new javax.swing.JLabel();
        lblBank = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        txtHealth = new javax.swing.JTextField();
        txtBank = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtdevice = new javax.swing.JTextField();
        txtmrno = new javax.swing.JTextField();
        lblmrno = new javax.swing.JLabel();
        lbldevice = new javax.swing.JLabel();
        lblip = new javax.swing.JLabel();
        txtip = new javax.swing.JTextField();
        btnupload = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtlicense = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtplate = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        lblTitle.setBackground(new java.awt.Color(0, 153, 153));
        lblTitle.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Profile");

        btnsave.setFont(new java.awt.Font("PingFang TC", 1, 14)); // NOI18N
        btnsave.setText("SAVE");
        btnsave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnsave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblName.setText("Name");

        lblCountry.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblCountry.setText("Country");

        lblDob.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblDob.setText("DOB");

        lblTelephone.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblTelephone.setText("Telephone");

        lblFax.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblFax.setText("FAX");

        lblEmail.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblEmail.setText("Email");

        lblssn.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblssn.setText("SSN");

        lblLicense.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblLicense.setText("License Number");

        lblLinkedin.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblLinkedin.setText("Linkedin");

        lblHealth.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblHealth.setText("Health Benificiary No");

        lblBank.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblBank.setText("Bank AC");

        txtName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtCountry.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCountryKeyReleased(evt);
            }
        });

        txtFax.setToolTipText("Ex: 111-111-2222");
        txtFax.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxKeyReleased(evt);
            }
        });

        txtTelephone.setToolTipText("Ex: 888-111-9876");
        txtTelephone.setActionCommand("<Not Set>");
        txtTelephone.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneActionPerformed(evt);
            }
        });
        txtTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelephoneKeyReleased(evt);
            }
        });

        txtLinkedin.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtLinkedin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLinkedinKeyReleased(evt);
            }
        });

        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        txtssn.setToolTipText("Ex: 11-333-9999");
        txtssn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtssnActionPerformed(evt);
            }
        });
        txtssn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtssnKeyReleased(evt);
            }
        });

        txtHealth.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthActionPerformed(evt);
            }
        });
        txtHealth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHealthKeyReleased(evt);
            }
        });

        txtBank.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtBank.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBankKeyReleased(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(51, 51, 51));

        txtdevice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtdevice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdeviceKeyReleased(evt);
            }
        });

        txtmrno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtmrno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmrnoKeyReleased(evt);
            }
        });

        lblmrno.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblmrno.setText("Medical Record No");

        lbldevice.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lbldevice.setText("Device Identifier");

        lblip.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        lblip.setText("Internet Protocols");

        txtip.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtipActionPerformed(evt);
            }
        });
        txtip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtipKeyReleased(evt);
            }
        });

        btnupload.setFont(new java.awt.Font("PingFang TC", 1, 14)); // NOI18N
        btnupload.setText("UPLOAD");
        btnupload.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnupload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));

        jLabel2.setForeground(new java.awt.Color(255, 51, 51));

        txtlicense.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtlicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicenseActionPerformed(evt);
            }
        });
        txtlicense.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlicenseKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("PingFang SC", 1, 14)); // NOI18N
        jLabel3.setText("Vehicle L.Plate");

        txtplate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplateActionPerformed(evt);
            }
        });
        txtplate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtplateKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmrno)
                    .addComponent(lbldevice, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblip)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicense)
                    .addComponent(lblLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHealth)
                    .addComponent(lblBank, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblssn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHealth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdevice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtmrno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtlicense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtplate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCountry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelephone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLinkedin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtssn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnupload, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBank, txtCountry, txtEmail, txtFax, txtHealth, txtLinkedin, txtName, txtTelephone, txtdevice, txtip, txtlicense, txtmrno, txtplate, txtssn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCountry))))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDob)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelephone)
                            .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblssn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtplate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicense))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLinkedin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHealth)
                            .addComponent(txtHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBank)
                            .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmrno)
                            .addComponent(txtmrno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldevice)
                            .addComponent(txtdevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblip))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupload, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBank, txtCountry, txtEmail, txtFax, txtHealth, txtLinkedin, txtName, txtTelephone, txtdevice, txtip, txtlicense, txtmrno, txtplate, txtssn});

    }// </editor-fold>//GEN-END:initComponents

    private void txtHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthActionPerformed
    
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, "Information Saved.");
        Info.setDob(jDateChooser1.getDate());
         
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtssnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtssnActionPerformed

    private void txtTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTelephoneActionPerformed

    private void txtipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtipActionPerformed

    private void btnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadActionPerformed
        // TODO add your handling code here:
       JFileChooser filechooser = new JFileChooser();
       //Specifying  the types of files that can be added by creating filter and specifying the constraints.
       FileNameExtensionFilter filter = new FileNameExtensionFilter("jpg,jpeg,gif,png ", "jpg", "jpeg","gif", "png");
       //Setting the filter to filechooser.
       filechooser.setFileFilter(filter);
       int selectedfile = filechooser.showOpenDialog(null);
       
       //Using an if function to check if the files selected is as per the specified constraints using APPROVE_OPTION
       if(selectedfile == JFileChooser.APPROVE_OPTION)
       {
           //Getting the selected file and storing it in file object.
           File file = filechooser.getSelectedFile();
           //Storing the absolute file name in a string variable SelectedImagePath
           Info.setImg_src(file.getAbsolutePath());
           
           //Displaying confirmation message saying "Image Saved".
           JOptionPane.showMessageDialog(null, "Image Uploaded.");   
       
    }//GEN-LAST:event_btnuploadActionPerformed
    }
    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtEmail.getText());
        if(!match.matches()){
            
              txtEmail.setBackground(Color.red);
        }
        else{
            
              txtEmail.setBackground(Color.white);
              Info.setEmail(txtEmail.getText());
            }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[a-zA-Z]{0,30}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtName.getText());
        if(!match.matches()){
            
            txtName.setBackground(Color.red);
        }
        else{
                txtName.setBackground(Color.white);
                Info.setName(txtName.getText());
        }
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtssnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtssnKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^\\d{3}-?\\d{2}-?\\d{4}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtssn.getText());
        if(!match.matches()){
            txtssn.setBackground(Color.red);
        }
        else{
                txtssn.setBackground(Color.white);
                Info.setSsn(txtssn.getText());
            }
        
    }//GEN-LAST:event_txtssnKeyReleased

    private void txtCountryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCountryKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[a-zA-Z]{0,30}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtCountry.getText());
        if(!match.matches()){
            
            txtCountry.setBackground(Color.red);
        }
        else{
            txtCountry.setBackground(Color.white);
            Info.setCountry(txtCountry.getText());
        }
    }//GEN-LAST:event_txtCountryKeyReleased

    private void txtLinkedinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLinkedinKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^https:\\/\\/[w]{3}\\.linkedin\\.com\\/.*$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtLinkedin.getText());
        if(!match.matches()){
            
            txtLinkedin.setBackground(Color.red);
        }
        else{
            txtLinkedin.setBackground(Color.white);
            Info.setLinkedin(txtLinkedin.getText());
        }
        
    }//GEN-LAST:event_txtLinkedinKeyReleased

    private void txtTelephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtTelephone.getText());
        if(!match.matches()){
            
            txtTelephone.setBackground(Color.red);
        }
        else{
            txtTelephone.setBackground(Color.white);
            Info.setPhone(txtTelephone.getText());
        }
    }//GEN-LAST:event_txtTelephoneKeyReleased

    private void txtdeviceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdeviceKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^([A-F0-9]{40})$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtdevice.getText());
        if(!match.matches()){
            
            txtdevice.setBackground(Color.red);
        }
        else{
            txtdevice.setBackground(Color.white);
            Info.setDevice(txtdevice.getText());
        }
    }//GEN-LAST:event_txtdeviceKeyReleased

    private void txtipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtipKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}↵\n" +
"(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtip.getText());
        if(!match.matches()){
            
            txtip.setBackground(Color.red);
        }
        else{
            txtip.setBackground(Color.white);
            Info.setIp(txtip.getText());
        }
    }//GEN-LAST:event_txtipKeyReleased

    private void txtHealthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHealthKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^\\b\\d[A-Z]{2}\\d-[A-Z]{2}\\d-[A-Z]{2}\\d{2}\\b $";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtHealth.getText());
        if(!match.matches()){
            txtHealth.setBackground(Color.red);
            
        }
        else{
            txtHealth.setBackground(Color.white);
            Info.setHealthno(txtHealth.getText());
        }
    }//GEN-LAST:event_txtHealthKeyReleased

    private void txtlicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicenseActionPerformed

    private void txtlicenseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicenseKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[A-Za-z][0-9/\\W/]{2,20}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtlicense.getText());
        if(!match.matches()){
            txtlicense.setBackground(Color.red);
            
        }
        else{
            txtlicense.setBackground(Color.white);
            Info.setLicense(txtlicense.getText());
        }
    }//GEN-LAST:event_txtlicenseKeyReleased

    private void txtplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtplateActionPerformed

    private void txtplateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplateKeyReleased
        // TODO add your handling code here:
        String PATTERN = "[A-HJ-NPR-Z0-9]{17}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtplate.getText());
        if(!match.matches()){
            txtplate.setBackground(Color.red);
            
        }
        else{
            txtplate.setBackground(Color.white);
            Info.setVehicle(txtplate.getText());
        }
    }//GEN-LAST:event_txtplateKeyReleased

    private void txtFaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^?[1-09]{7,}$/";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtFax.getText());
        if(!match.matches()){
            txtFax.setBackground(Color.red);
        }
        else{
                txtFax.setBackground(Color.white);
                Info.setFax(txtFax.getText());
        }
    }//GEN-LAST:event_txtFaxKeyReleased

    private void txtBankKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^\\W*\\d{8,17}\\b $";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtBank.getText());
        if(!match.matches()){
            txtBank.setBackground(Color.red);
        }
        else{
                txtBank.setBackground(Color.white);
                Info.setBankac(txtBank.getText());
        }
    }//GEN-LAST:event_txtBankKeyReleased

    private void txtmrnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmrnoKeyReleased
        // TODO add your handling code here:
        String PATTERN ="^[1-09]{6}$";
        Pattern p = Pattern.compile(PATTERN);
        Matcher match = p.matcher(txtmrno.getText());
        if(!match.matches()){
            txtmrno.setBackground(Color.red);
        }
        else{
                txtmrno.setBackground(Color.white);
                Info.setMrn(txtBank.getText());
        }
    }//GEN-LAST:event_txtmrnoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupload;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbldevice;
    private javax.swing.JLabel lblip;
    private javax.swing.JLabel lblmrno;
    private javax.swing.JLabel lblssn;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtHealth;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtdevice;
    private javax.swing.JTextField txtip;
    private javax.swing.JTextField txtlicense;
    private javax.swing.JTextField txtmrno;
    private javax.swing.JTextField txtplate;
    private javax.swing.JTextField txtssn;
    // End of variables declaration//GEN-END:variables
}
